### ISSUE TITLE
Filters when using quick_open via toggle

### ISSUE THREAD

**Issue by ghost** [rgieseke/textredux#60] opened 2020-05-27 15:40 UTC
It seems `lfs.default_filter` does not apply when using *quick_open* via the toggle (default: ctrl+s in the open dialog).  
I tried to fix this here: https://github.com/loomer/textredux/commit/b200c1e880a6a1a344ea243a97d0331c2b832f3f  
The code is rather brittle though as it was originally just designed to make *quick_open* work again after it was broken by some TA updates.  It makes some assumptions about the structure of filter entries but does work.
The existing filter system in TR seems quite messy and overhauling all of it would probably be a fairly big task.

What is your take on this?

**Comment by rgieseke** [comment] 2020-06-03 09:37
Agreed, it's a big task and hasn't caught up with TA's API changes over time ... don't know how to best tackle it ...

**Comment by snoopy** [comment] 2021-06-11 16:11
Should be fixed with https://github.com/rgieseke/textredux/commit/2b12ad657a22f4ca9859d3ab747c92b75a1bf3a2  
At least I can't reproduce the issue described in the OP so this can probably be closed?

**Comment by rgieseke** [comment] 2021-06-11 16:27
Agreed!

**Closed** 2021-06-11 16:28 UTC
